obstacle_range: 6.0
raytrace_range: 6.0

footprint: [[0.6, 0.33], [0, 0.38], [0, -0.33], [0.6, -0.33]]
footprint_padding: 0.03

#robot_radius: 0.37

inflation_radius: 0.5
cost_scaling_factor: 5.0

transform_tolerance: 0.5
map_type: costmap

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, expected_update_rate: 0.0}