# NavfnROS:
#   visualize_potential: false    
#   allow_unknown: false          
                                
#   planner_window_x: 0.0         
#   planner_window_y: 0.0         

#   default_tolerance: 0.0

BaseGlobalPlanner:
  allow_unknown: true
  use_dijkstra: false #Use A* instead
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false

  visualize_potential: false    
  allow_unknown: false 